default:
  n_tokens: 10  # Number of text tokens to consider, e.g. when building a text embedding model
  n_rows: 100  # Number of rows (observations) to consider, e.g., from the train-sample, useful for shortening longish analyses during debugging
  v_folds: 2   # Number of folds in cross validation
  n_repeats: 1   # Number of repeats in cross validation
  verbose: TRUE  # whether the output of functions should be verbose
  tinyfy: TRUE  # whether the data samples should be shortened by drawing random samples, useful for shortening longish analyses during debugging
  n_grid: 2 # number of tuning parameters to consider during tuning
  n_workers: 3  # number of computer cores to use
  
  
dev:
  n_tokens: 100
  n_rows: 100
  v_folds: 4   
  n_repeats: 1 
  verbose: TRUE
  tinyfy: TRUE
  n_grid: 1
  n_workers: 3  
  
  
production:
  n_tokens: Inf
  n_rows: Inf
  v_folds: 10
  n_repeats: 2
  verbose: FALSE
  tinyfy: FALSE
  n_grid: 25
  n_workers: 3  
  
